version: "3.4"
services:
  zookeeper:
    container_name: apache-zookeeper
    image: zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: apache-kafka
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.106:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper